### ISSUE TITLE
Obsidian Importer Status Tracker

### ISSUE THREAD

**Issue by LuccaHellriegel** [tanainc/tana-import-tools#3]
**NOT UNDER ACTIVE DEVELOPMENT - PROVIDED AS IS, SHOULD WORK FOR MANY CASES**

**Test the converter here: https://luccahellriegel.github.io/tana-import-tools/**

I will use this issue to track the TODOs for the Obsidian Importer and let other people contribute. Please post all the missing features below. I will edit the issue as we go along.

If possible include an example for the found issues so that I can replicate it / more easily figure out how to integrate it.

IN PROGRESS: (holiday)
 
Status:
- [ ] Task Plugin Queries
- [ ] Dataview attributes without values
- [ ] footnotes: https://tanacommunity.slack.com/archives/C044X2ZC335/p1665948771836759
- [ ] normal markdown links \[My Link\]\(My%20Link.md\) and also with URL (URL works out of the box)
- [ ] callouts / block quotes as own node with #block-quote 
- [ ] embeds
- [ ] Dataview Attributes: https://github.com/blacksmithgu/obsidian-dataview (standard should already work, just not inline)
- [ ] Dataview Queries
- [ ] Dataview tables
- [ ] Markdown tables
- [ ] Frontmatter Comments
- [ ] Frontmatter sub-values that start with empty space instead of "-"
- [ ] improve test separation / add more separate integration tests
- [x] proper detection of "non"-tags (obsidian has pretty clear guidlines: https://help.obsidian.md/How+to/Working+with+tags)
- [x] perf tuning: bring down runtime for huge vault-zips from 60 sec to 30
- [x] support for web and local version
- [x] different file-path links (shortest: [[file]], absolute: [[folder/file]])
- [x] tags to supertags
- [x] aliases
- [x] heading links
- [x] invalid heading links (either missing or has trailing #-symbols)
- [x] block links
- [x] invalid block links
- [x] codeblocks
- [x] Frontmatter custom Attributes (need Attribute/Field Definition)
- [x] Summary for fields
- [x] Frontmatter tags 
- [x] Remove Frontmatter that is only Obsidian specific (publish / cssclass / aliases)
- [x] daily notes / date notes
- [x] todos
- [x] plain markdown image links with urls

Backburner:
* images (need Firebase URLs, not possible without an API - possibly your own file-upload API)
* Headings with Heading Links or normal links in them
* relative file paths: [[./file]] (this would require checking the folder again and saving filepath<->UID pairs)
* callouts / block quotes - while they are split into their own node, they are not native to Tana and will be marked with #block-quote
* #[[bla bla]] links -> currently we just remove the link here

**Comment by TanaRob** [comment]
Aliases

[[page name|alias]]

Header references

**Comment by vicrdguez** [comment]
Have obsidian callouts an equivalent in Tana? or they will be translated just as a quote block?

**Comment by LuccaHellriegel** [comment]
- [x] Added some documentation about how the importer works (much more complicated conversion than another graph format)
- [x] Folder Structure is taken into account (nodes are nested under their respective folder-nodes)
- [x] Links inside files are replaced with appropriate UIDs
- [x] Missing nodes are created separately (up for debate, but they are tracked - easy to change now)

**Comment by tomasztatar** [comment]
Hi.
I had problems with importing TIF files when name attributes contained full Windows paths for example:
  "name": "C:\Users\qwerty\OneDrive - company\Documents\iCloud-Obsidian-notes"
or
  "name": "C:\\Users\\qwerty\\OneDrive - company\\Documents\\iCloud-Obsidian-notes\\--- PARA",

Tana refused to import it. When I manually replaced names to:
  "name": "iCloud-Obsidian-notes", 
  "name": "--- PARA",
it worked.

I am not sure what requirements does Tana enforce on name attribute.

As for web zip converter, I always have error:
```
An Error occured.

It probably has to do with a not properly zipped vault.
Please check the text at the top again.

Content of Error (please post in the Slack and tag me):

TypeError: Cannot read properties of undefined (reading 'children')
at lu.readDirectory (https://luccahellriegel.github.io/tana-import-tools/assets/index.b5f269bd.js:2:37178)
at wp (https://luccahellriegel.github.io/tana-import-tools/assets/index.b5f269bd.js:25:1465)
at cc (https://luccahellriegel.github.io/tana-import-tools/assets/index.b5f269bd.js:25:1794)
at bp (https://luccahellriegel.github.io/tana-import-tools/assets/index.b5f269bd.js:36:10)
at async HTMLInputElement.<anonymous> (https://luccahellriegel.github.io/tana-import-tools/assets/index.b5f269bd.js:44:687)

```

I am willing to help with troubleshooting it.

**Comment by tomasztatar** [comment]
Hi @LuccaHellriegel 

No, I missed requirement about naming zip file. Now I retested and web converter worked fine. Additionally TIF file does not contain full Windows paths and imports successfully into Tana. Thanks.

But I have another issue - my Obsidian files contain tags, usually at the end, in separate paragraph. They convert to Tana tags, but are located as separate sub-node. That means that listing tagged nodes list their empty tag-only nodes. I would expect that file-level node is tagged (as it is in Obsidian).

![image](https://user-images.githubusercontent.com/55286827/209301057-4d14699c-3708-45c5-aa15-48fcc72c2709.png)

**Comment by SutanuNandigrami** [comment]
#29

**Comment by LuccaHellriegel** [comment]
Not under active development anymore.
